# Generated by Django 3.2.16 on 2022-10-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='backend.plant'),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('plant', 'timestamp')},
        ),
    ]
