# Generated by Django 3.2.16 on 2022-10-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_auto_20221014_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
